### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by PeterMitrano** [WPISmartmouse/Smartmouse_2017#3]
- [x] make the robot not faceplant walls
 - [ ] update simulation to match real robot performance
 - [x] fix what the robot does when it returns to the start
 - [ ] implement save and reload maze with SD
 - [ ] implement speed run and have it based on buttons
 - [x] try arcturn
 - [x] prevent it from following off the end of walls
 - [x] protect encoders with new motor caps
 - [x] improve battery holder
